[2025-02-24T04:25:54.810+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:25:54.830+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_landings3.create_missing_tables manual__2025-02-24T04:25:27.524048+00:00 [queued]>
[2025-02-24T04:25:54.841+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_landings3.create_missing_tables manual__2025-02-24T04:25:27.524048+00:00 [queued]>
[2025-02-24T04:25:54.841+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-24T04:25:54.864+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_missing_tables> on 2025-02-24 04:25:27.524048+00:00
[2025-02-24T04:25:54.867+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2025-02-24T04:25:54.871+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_landings3', 'create_missing_tables', 'manual__2025-02-24T04:25:27.524048+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_landings3.py', '--cfg-path', '/tmp/tmpzrg7zdjy']
[2025-02-24T04:25:54.874+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask create_missing_tables
[2025-02-24T04:25:54.928+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_landings3.create_missing_tables manual__2025-02-24T04:25:27.524048+00:00 [running]> on host c9f7a13d5dc6
[2025-02-24T04:25:55.008+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_landings3' AIRFLOW_CTX_TASK_ID='create_missing_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-02-24T04:25:27.524048+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-24T04:25:27.524048+00:00'
[2025-02-24T04:25:55.010+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:25:55.132+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/infra/airflow/dags/dag_landings3.py", line 178, in create_missing_tables
    create_table_in_duckdb(con, dp_table_name, table_fields[base])
  File "/home/infra/airflow/dags/dag_landings3.py", line 164, in create_table_in_duckdb
    con.execute(query)
duckdb.duckdb.CatalogException: Catalog Error: Table with name "dp_ingredients_staging" already exists!
[2025-02-24T04:25:55.176+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=dag_landings3, task_id=create_missing_tables, run_id=manual__2025-02-24T04:25:27.524048+00:00, execution_date=20250224T042527, start_date=20250224T042554, end_date=20250224T042555
[2025-02-24T04:25:55.252+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:25:55.254+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task create_missing_tables (Catalog Error: Table with name "dp_ingredients_staging" already exists!; 179)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/infra/airflow/dags/dag_landings3.py", line 178, in create_missing_tables
    create_table_in_duckdb(con, dp_table_name, table_fields[base])
  File "/home/infra/airflow/dags/dag_landings3.py", line 164, in create_table_in_duckdb
    con.execute(query)
duckdb.duckdb.CatalogException: Catalog Error: Table with name "dp_ingredients_staging" already exists!
[2025-02-24T04:25:55.299+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-24T04:25:55.330+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:25:55.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
